# Generated by Django 4.1 on 2022-08-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copamundial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('equipos', models.CharField(max_length=100)),
            ],
        ),
    ]
